int8-batch-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-max-gpu-resnet50v1-5-inference
  cmd: quickstart/inference_block_format.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: int8
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    NUM_OAM: '4'
