MobileNet-V1 Accuracy fp32:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/accuracy.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/accuracy_fp32
    BATCH_SIZE: '100'
    PRECISION: fp32
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/accuracy_fp32
    dst: /output/tf-mobilenet-v1-inference/accuracy_fp32
MobileNet-V1 Accuracy bf16:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/accuracy.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/accuracy_bf16
    BATCH_SIZE: '100'
    PRECISION: bfloat16
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/accuracy_bf16
    dst: /output/tf-mobilenet-v1-inference/accuracy_bf16
MobileNet-V1 Accuracy int8:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/accuracy.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/accuracy_int8
    BATCH_SIZE: '100'
    PRECISION: int8
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/accuracy_int8
    dst: /output/tf-mobilenet-v1-inference/accuracy_int8
MobileNet-V1 Realtime Inference fp32:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/inference_realtime_multi_instance.sh --benchmark-only --num-intra-threads 4 --num-inter-threads 1 --verbose
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/realtime_fp32
    BATCH_SIZE: '1'
    PRECISION: fp32
    OMP_NUM_THREADS: '4'
    KMP_AFFINITY: granularity=fine,verbose,compact,1,0
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/realtime_fp32
    dst: /output/tf-mobilenet-v1-inference/realtime_fp32
MobileNet-V1 Realtime Inference bf16:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/inference_realtime_multi_instance.sh --benchmark-only --num-intra-threads 4 --num-inter-threads 1 --verbose
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/realtime_bf16
    BATCH_SIZE: '1'
    PRECISION: bfloat16
    OMP_NUM_THREADS: '4'
    KMP_AFFINITY: granularity=fine,verbose,compact,1,0
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/realtime_bf16
    dst: /output/tf-mobilenet-v1-inference/realtime_bf16
MobileNet-V1 Realtime Inference int8:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/inference_realtime_multi_instance.sh --benchmark-only --num-intra-threads 4 --num-inter-threads 1 --verbose
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/realtime_int8
    BATCH_SIZE: '1'
    PRECISION: int8
    OMP_NUM_THREADS: '4'
    KMP_AFFINITY: granularity=fine,verbose,compact,1,0
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/realtime_int8
    dst: /output/tf-mobilenet-v1-inference/realtime_int8
MobileNet-V1 Throughput fp32:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/inference_throughput_multi_instance.sh --benchmark-only --num-intra-threads 64 --num-inter-threads 1 --verbose
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/throughput_fp32
    BATCH_SIZE: '448'
    PRECISION: fp32
    OMP_NUM_THREADS: '64'
    KMP_AFFINITY: granularity=fine,verbose,compact,1,0
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/throughput_fp32
    dst: /output/tf-mobilenet-v1-inference/throughput_fp32
MobileNet-V1 Throughput bf16:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/inference_throughput_multi_instance.sh --benchmark-only --num-intra-threads 64 --num-inter-threads 1 --verbose
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/throughput_bf16
    BATCH_SIZE: '448'
    PRECISION: bfloat16
    OMP_NUM_THREADS: '64'
    KMP_AFFINITY: granularity=fine,verbose,compact,1,0
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/throughput_bf16
    dst: /output/tf-mobilenet-v1-inference/throughput_bf16
MobileNet-V1 Throughput int8:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${OS:-ubuntu}-image-recognition-tf-mobilenet-v1-inference
  cmd: /bin/bash quickstart/inference_throughput_multi_instance.sh --benchmark-only --num-intra-threads 64 --num-inter-threads 1 --verbose
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-mobilenet-v1-inference/throughput_int8
    BATCH_SIZE: '448'
    PRECISION: int8
    OMP_NUM_THREADS: '64'
    KMP_AFFINITY: granularity=fine,verbose,compact,1,0
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: $PWD/output/tf-mobilenet-v1-inference/throughput_int8
    dst: /output/tf-mobilenet-v1-inference/throughput_int8
