bf16-single-tile-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-gpu-resnet50v1-5-training
  cmd: bash run_model.sh
  ipc: host
  device: ["/dev/dri"]
  env:
    PRECISION: BF16
    NUM_ITERATIONS: '20'
    BATCH_SIZE: '256'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    MULTI_TILE: 'False'
    PLATFORM: 'Max'
    NUM_DEVICES: '1'
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /dev/dri
      dst: /dev/dri
    - src: /dev/dri/by-path
      dst: /dev/dri/by-path
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
