---
tf-max-gpu-bert-large-training:
  image_name: intel/language-modeling:tf-max-gpu-bert-large-training
  tests:
  - test_name: BERT Large BF16 Training
    env_vars:
      PRECISION: bfloat16
      Tile: 2
      BERT_LARGE_DIR: /pytorch/wwm_uncased_L-24_H-1024_A-16
      SCRIPT: quickstart/bfloat16_training.sh
      OUTPUT_DIR: /output/tf-max-gpu-bert-large-training
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      OUTPUT_DIR: /output/tf-max-gpu-bert-large-training
      /dev/dri: /dev/dri
      BERT_LARGE_DIR: /pytorch/wwm_uncased_L-24_H-1024_A-16
  - test_name: BERT Large BF16 HVD Training
    env_vars:
      PRECISION: bfloat16
      Tile: 1
      BERT_LARGE_DIR: /pytorch/wwm_uncased_L-24_H-1024_A-16
      SCRIPT: quickstart/bfloat16_training_hvd.sh
      OUTPUT_DIR: /output/tf-max-gpu-bert-large-training/hvd
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      OUTPUT_DIR: /output/tf-max-gpu-bert-large-training/hvd
      /dev/dri: /dev/dri
      BERT_LARGE_DIR: /pytorch/wwm_uncased_L-24_H-1024_A-16
