repos:
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
      - id: pylint
        args: [--rcfile=.github/linters/.pylintrc]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [--config-file=.github/linters/.yaml-lint.yml]
