fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
fp16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
fp16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
fp16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
bf16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
int8-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
int8-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
int8-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
bf32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: REALTIME
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
bf32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: THROUGHPUT
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
bf32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-yolov7-inference
  cmd: bash run_model.sh
  cap_add: SYS_NICE
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    TORCH_INDUCTOR: '0'
    TEST_MODE: ACCURACY
    DATASET_DIR: /pytorch/yolov7/data
    CHECKPOINT_DIR: /pytorch/yolov7/model
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/yolov7/data
      dst: /pytorch/yolov7/data
    - src: /pytorch/yolov7/model
      dst: /pytorch/yolov7/model
