fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-inference
  cmd: quickstart/inference_realtime.sh fp32 jit
  env:
    PRECISION: fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-inference
  cmd: quickstart/inference_throughput.sh fp32 jit
  env:
    PRECISION: fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-inference
  cmd: quickstart/accuracy.sh fp32 jit
  env:
    PRECISION: fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-inference
  cmd: quickstart/inference_realtime.sh bf16 jit
  env:
    PRECISION: bf16
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-inference
  cmd: quickstart/inference_throughput.sh bf16 jit
  env:
    PRECISION: bf16
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-inference
  cmd: quickstart/accuracy.sh bf16 jit
  env:
    PRECISION: bf16
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
