170-int80online:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: INT8
    NUM_ITERATIONS: '5000'
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
  volumes:
    - src: /tmp
      dst: /tmp
170-int8-batch:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: INT8
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
  volumes:
    - src: /tmp
      dst: /tmp
170-fp32-online:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: FP32
    NUM_ITERATIONS: '5000'
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
  volumes:
    - src: /tmp
      dst: /tmp
170-fp32-batch:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: FP32
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
  volumes:
    - src: /tmp
      dst: /tmp
170-fp16-online:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: FP16
    NUM_ITERATIONS: '5000'
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
  volumes:
    - src: /tmp
      dst: /tmp
170-fp16-batch:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-flex-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION: FP16
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
  volumes:
    - src: /tmp
      dst: /tmp
