fp32-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-spr-bert-large-inference
  cmd: quickstart/run_multi_instance_realtime.sh
  shm-size: 8G
  env:
    PRECISION: fp32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-spr-bert-large-inference/quickstart/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    EVAL_SCRIPT: /workspace/pytorch-spr-bert-large-inference/quickstart/transformers/examples/legacy/question-answering/run_squad.py
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-spr-bert-large-inference
  cmd: quickstart/run_multi_instance_throughput.sh
  shm-size: 8G
  env:
    PRECISION: fp32
    EVAL_DATA_FILE: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    INT8_CONFIG: /workspace/pytorch-spr-bert-large-inference/quickstart/configure.json
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pytorch-bert-squad-model
    EVAL_SCRIPT: /workspace/pytorch-spr-bert-large-inference/quickstart/transformers/examples/legacy/question-answering/run_squad.py
  volumes:
    - src: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
      dst: /tf_dataset/dataset/data-bert-squad/squad-data/mini-dev-v1.1.json
    - src: /pytorch/pytorch-bert-squad-model
      dst: /pytorch/pytorch-bert-squad-model
