170-batch-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-pytorch-flex-gpu-yolov5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env: 
    BATCH_SIZE: '32'
    NUM_ITERATIONS: '500'
    PRECISION: fp16
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
170-online-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-pytorch-flex-gpu-yolov5-inference
  cmd: bash run_model.sh
  ipc: host
  device: /dev/dri
  env: 
    BATCH_SIZE: '1'
    NUM_ITERATIONS: '5000'
    PRECISION: fp16
    MULTI_TILE: 'False'
    PLATFORM: 'Flex'
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tmp
      dst: /tmp
