---
pytorch-flex-gpu-yolov4-inference:
  image_name: intel/object-detection:pytorch-flex-gpu-yolov5-inference
  tests:
  - test_name: YOLOv5 BS 32 inference
    env_vars:
      SCRIPT: quickstart/inference.sh
      BATCH_SIZE: 32
      IMAGE_FILE: /pytorch/yolov4/image/000000581918.jpg
      OUTPUT_DIR: /output/pytorch-flex-gpu-yolov5-inference
      NUM_ITERATIONS: 500
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      IMAGE_FILE: /pytorch/yolov4/image/000000581918.jpg
      OUTPUT_DIR: /output/pytorch-flex-gpu-yolov5-inference
  - test_name: YOLOv5 BS 1 inference
    env_vars:
      SCRIPT: quickstart/inference.sh
      BATCH_SIZE: 1
      IMAGE_FILE: /pytorch/yolov4/image/000000581918.jpg
      OUTPUT_DIR: /output/pytorch-flex-gpu-yolov5-inference
      NUM_ITERATIONS: 5000
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      IMAGE_FILE: /pytorch/yolov4/image/000000581918.jpg
      OUTPUT_DIR: /output/pytorch-flex-gpu-yolov5-inference
