max-bf16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: ["/dev/dri"]
  env:
    PRECISION: BF16
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    PLATFORM: 'Max'
    NUM_DEVICES: '2'
  volumes:
    - src: /tmp
      dst: /tmp
max-fp16-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: ["/dev/dri"]
  env:
    PRECISION: FP16
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    PLATFORM: 'Max'
    NUM_DEVICES: '2'
  volumes:
    - src: /tmp
      dst: /tmp
max-fp32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: ["/dev/dri"]
  env:
    PRECISION: FP32
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    PLATFORM: 'Max'
    NUM_DEVICES: '2'
  volumes:
    - src: /tmp
      dst: /tmp
max-tf32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: ["/dev/dri"]
  env:
    PRECISION: TF32
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    PLATFORM: 'Max'
    NUM_DEVICES: '2'
  volumes:
    - src: /tmp
      dst: /tmp
int8-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-pytorch-gpu-resnet50v1-5-inference
  cmd: bash run_model.sh
  ipc: host
  device: ["/dev/dri"]
  env:
    PRECISION: INT8
    NUM_ITERATIONS: '500'
    BATCH_SIZE: '1024'
    OUTPUT_DIR: /tmp
    MULTI_TILE: 'True'
    PLATFORM: 'Max'
    NUM_DEVICES: '2'
  volumes:
    - src: /tmp
      dst: /tmp
