batch-170-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: quickstart/batch_inference.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION : int8
    GPU_TYPE: flex_series
    OUTPUT_DIR: /tmp
online-170-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: quickstart/online_inference.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION : int8
    GPU_TYPE: flex_series
    OUTPUT_DIR: /tmp
batch-140-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: quickstart/flex_multi_card_batch_inference.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION : int8
    GPU_TYPE: flex_series
    BATCH_SIZE: '256'
    OUTPUT_DIR: /tmp
batch-140-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: quickstart/flex_multi_card_online_inference.sh
  ipc: host
  device: /dev/dri
  cap_add: SYS_NICE
  env:
    PRECISION : int8
    GPU_TYPE: flex_series
    BATCH_SIZE: '1'
    OUTPUT_DIR: /tmp
170-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-flex-gpu-resnet50v1-5-inference
  cmd: quickstart/accuracy.sh
  ipc: host
  device: /dev/dri
  env:
    PRECISION : int8
    GPU_TYPE: flex_series
    OUTPUT_DIR: /tmp
  volumes:
    - src: /tf_dataset/dataset/TF_Imagenet_FullData
      dst: /tf_dataset/dataset/TF_Imagenet_FullData
