ResNet50 v1.5 BFloat32 accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/accuracy.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/bf32_accuracy
    BATCH_SIZE: '100'
    PRECISION: bfloat32
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/bf32_accuracy
    dst: /output/tf-spr-resnet50v1-5-inference/bf32_accuracy
ResNet50 v1.5 BFloat16 accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/accuracy.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/bf16_accuracy
    BATCH_SIZE: '100'
    PRECISION: bfloat16
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/bf16_accuracy
    dst: /output/tf-spr-resnet50v1-5-inference/bf16_accuracy
ResNet50 v1.5 fp32 accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/accuracy.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/fp32_accuracy
    BATCH_SIZE: '100'
    PRECISION: fp32
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/fp32_accuracy
    dst: /output/tf-spr-resnet50v1-5-inference/fp32_accuracy
ResNet50 v1.5 int8 accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/accuracy.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/int8_accuracy
    BATCH_SIZE: '100'
    PRECISION: int8
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/int8_accuracy
    dst: /output/tf-spr-resnet50v1-5-inference/int8_accuracy
ResNet50 v1.5 bfloat32 realtime inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_realtime.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/bf32_realtime
    BATCH_SIZE: '1'
    PRECISION: bfloat32
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/bf32_realtime
    dst: /output/tf-spr-resnet50v1-5-inference/bf32_realtime
ResNet50 v1.5 bfloat16 realtime inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_realtime.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/bf16_realtime
    BATCH_SIZE: '1'
    PRECISION: bfloat16
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/bf16_realtime
    dst: /output/tf-spr-resnet50v1-5-inference/bf16_realtime
ResNet50 v1.5 fp32 realtime inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_realtime.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/fp32_realtime
    BATCH_SIZE: '1'
    PRECISION: fp32
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/fp32_realtime
    dst: /output/tf-spr-resnet50v1-5-inference/fp32_realtime
ResNet50 v1.5 int8 realtime inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_realtime.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/int8_realtime
    BATCH_SIZE: '1'
    PRECISION: int8
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/int8_realtime
    dst: /output/tf-spr-resnet50v1-5-inference/int8_realtime
ResNet50 v1.5 bfloat32 throughput inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_throughput.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/bf32_throughput
    BATCH_SIZE: '448'
    PRECISION: bfloat32
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/bf32_throughput
    dst: /output/tf-spr-resnet50v1-5-inference/bf32_throughput
ResNet50 v1.5 bfloat16 throughput inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_throughput.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/bf16_throughput
    BATCH_SIZE: '448'
    PRECISION: bfloat16
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/bf16_throughput
    dst: /output/tf-spr-resnet50v1-5-inference/bf16_throughput
ResNet50 v1.5 fp32 throughput inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_throughput.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/fp32_throughput
    BATCH_SIZE: '448'
    PRECISION: fp32
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/fp32_throughput
    dst: /output/tf-spr-resnet50v1-5-inference/fp32_throughput
ResNet50 v1.5 int8 throughput inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_throughput.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/int8_throughput
    BATCH_SIZE: '448'
    PRECISION: int8
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/int8_throughput
    dst: /output/tf-spr-resnet50v1-5-inference/int8_throughput
ResNet50 v1.5 bfloat16 weightsharing inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_realtime_weightsharing.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/bf16_weightsharing
    BATCH_SIZE: '1'
    PRECISION: bfloat16
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/bf16_weightsharing
    dst: /output/tf-spr-resnet50v1-5-inference/bf16_weightsharing
ResNet50 v1.5 int8 weightsharing inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-image-recognition-tf-spr-resnet50v1-5-inference
  cmd: /bin/bash quickstart/inference_realtime_weightsharing.sh
  env:
    DATASET_DIR: /tf_dataset/dataset/TF_Imagenet_FullData
    OUTPUT_DIR: /output/tf-spr-resnet50v1-5-inference/int8_weightsharing
    BATCH_SIZE: '1'
    PRECISION: int8
  shm_size: 8G
  privileged: true
  init: true
  volumes:
  - src: /tf_dataset/dataset/TF_Imagenet_FullData
    dst: /tf_dataset/dataset/TF_Imagenet_FullData
  - src: /output/tf-spr-resnet50v1-5-inference/int8_weightsharing
    dst: /output/tf-spr-resnet50v1-5-inference/int8_weightsharing
