---
pytorch-flex-gpu-stable-diffusion-inference:
  image_name: intel/generative-ai:pytorch-flex-gpu-stable-diffusion-inference
  tests:
  - test_name: Stable Diffusion FP32 inference
    env_vars:
      PRECISION: fp32
      SCRIPT: quickstart/online_inference.sh
      BATCH_SIZE: 1
      OUTPUT_DIR: /output/flex-gpu-stable-diffusion-inference
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      OUTPUT_DIR: /output/flex-gpu-stable-diffusion-inference
  - test_name: Stable Diffusion FP16 inference
    env_vars:
      PRECISION: fp16
      SCRIPT: quickstart/online_inference.sh
      BATCH_SIZE: 1
      OUTPUT_DIR: /output/flex-gpu-stable-diffusion-inference
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      OUTPUT_DIR: /output/flex-gpu-stable-diffusion-inference
