fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-training
  cmd: quickstart/training.sh
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData/
    TRAINING_EPOCHS: '1'
  volumes:
    - src: /pytorch/Imagenet_FullData/
      dst: /pytorch/Imagenet_FullData/
avx-fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-training
  cmd: quickstart/training.sh
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData/
    TRAINING_EPOCHS: '1'
  volumes:
    - src: /pytorch/Imagenet_FullData/
      dst: /pytorch/Imagenet_FullData/
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-training
  cmd: quickstart/training.sh
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData/
    TRAINING_EPOCHS: '1'
  volumes:
    - src: /pytorch/Imagenet_FullData/
      dst: /pytorch/Imagenet_FullData/
bf32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-training
  cmd: quickstart/training.sh
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData/
    TRAINING_EPOCHS: '1'
  volumes:
    - src: /pytorch/Imagenet_FullData/
      dst: /pytorch/Imagenet_FullData/

