fp32-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
fp16-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
    DNNL_MAX_CPU_ISA: AVX512_CORE_AMX_FP16
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
avx-fp32-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
bf16-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
int8-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
avx-int8-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
bf32-online_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: REALTIME
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
fp32-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
    TORCH_INDUCTOR: '0'
    BATCH_SIZE: '40'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
fp16-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
    DNNL_MAX_CPU_ISA: AVX512_CORE_AMX_FP16
    TORCH_INDUCTOR: '0'
    BATCH_SIZE: '40'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
avx-fp32-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
    TORCH_INDUCTOR: '0'
    BATCH_SIZE: '40'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
bf16-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
    TORCH_INDUCTOR: '0'
    BATCH_SIZE: '40'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
int8-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
    TORCH_INDUCTOR: '0'
    BATCH_SIZE: '40'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
avx-int8-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
    TORCH_INDUCTOR: '0'
    BATCH_SIZE: '40'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
bf32-throughput_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: THROUGHPUT
    TORCH_INDUCTOR: '0'
    BATCH_SIZE: '40'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
    - src: /tmp
      dst: /tmp
fp32-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
fp16-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
    DNNL_MAX_CPU_ISA: AVX512_CORE_AMX_FP16
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-fp32-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-fp32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf16-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
int8-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
avx-int8-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: avx-int8
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
bf32-accuracy_inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-pytorch-image-recognition-resnet50-inference
  cmd: sh -c " cd models_v2/pytorch/resnet50/inference/cpu && ./run_model.sh"
  shm-size: 8G
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/Imagenet_FullData
    TEST_MODE: ACCURACY
    TORCH_INDUCTOR: '0'
  volumes:
    - src: /pytorch/Imagenet_FullData
      dst: /pytorch/Imagenet_FullData
