max-fp32-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-pytorch-gpu-distilbert-inference
  cmd: bash run_model.sh
  ipc: host
  device: ["/dev/dri"]
  env:
    MULTI_TILE: 'False'
    PLATFORM: Max
    BATCH_SIZE: '32'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/hdf5_seq_512/
    PRECISION: FP32
    NUM_ITERATIONS: '300'
  volumes:
    - src: /pytorch/hdf5_seq_512/
      dst: /pytorch/hdf5_seq_512/
    - src: /tmp
      dst: /tmp
