---
tf-flex-gpu-ssd-mobilenet-inference:
  image_name: intel/object-detection:tf-flex-gpu-ssd-mobilenet-inference
  tests:
  - test_name: SSD-MobileNet INT8 Batch inference
    env_vars:
      PRECISION: int8
      SCRIPT: quickstart/batch_inference.sh
      BATCH_SIZE: 1024
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      DATASET_DIR: /tf_dataset/dataset/SSDMobilenet
      OUTPUT_DIR: /output/tf-flex-gpu-ssd-mobilenet-inference
  - test_name: SSD-MobileNet INT8 Online inference
    env_vars:
      PRECISION: int8
      SCRIPT: quickstart/online_inference.sh
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      DATASET_DIR: /tf_dataset/dataset/SSDMobilenet
      OUTPUT_DIR: /output/tf-flex-gpu-ssd-mobilenet-inference
  - test_name: SSD-MobileNet INT8 Accuracy inference
    env_vars:
      PRECISION: int8
      SCRIPT: quickstart/accuracy.sh
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      DATASET_DIR: /tf_dataset/dataset/SSDMobilenet
      OUTPUT_DIR: /output/tf-flex-gpu-ssd-mobilenet-inference

