---
tf-flex-gpu-ssd-mobilenet-inference:
  image_name: intel/object-detection:tf-flex-gpu-ssd-mobilenet-inference
  tests:
  - test_name: SSD-MobileNet INT8 Batch inference on Flex 140
    env_vars:
      PRECISION: int8
      SCRIPT: quickstart/flex_multi_card_batch_inference.sh
      BATCH_SIZE: 256
      DATASET_DIR: /tf_dataset/dataset/SSDMobilenet
      OUTPUT_DIR: /output/tf-flex-gpu-ssd-mobilenet-inference
      DOCKER_ARGS: --cap-add=SYS_NICE --ipc=host --privileged --device=/dev/dri
    volumes:
      DATASET_DIR: /tf_dataset/dataset/SSDMobilenet
      OUTPUT_DIR: /output/tf-flex-gpu-ssd-mobilenet-inference
  - test_name: SSD-MobileNet INT8 Online inference on Flex 140
    env_vars:
      PRECISION: int8
      SCRIPT: quickstart/flex_multi_card_online_inference.sh
      BATCH_SIZE: 1
      DATASET_DIR: /tf_dataset/dataset/SSDMobilenet
      OUTPUT_DIR: /output/tf-flex-gpu-ssd-mobilenet-inference
      DOCKER_ARGS: --cap-add=SYS_NICE --ipc=host --privileged --device=/dev/dri
    volumes:
      DATASET_DIR: /tf_dataset/dataset/SSDMobilenet
      OUTPUT_DIR: /output/tf-flex-gpu-ssd-mobilenet-inference
