fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-training
  cmd: quickstart/training.sh fp32
  env:
    PRECISION: fp32
    BATCH_SIZE: '56'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /localdisk/sharvils/data/coco
  volumes:
    - src: /localdisk/sharvils/data/coco
      dst: /localdisk/sharvils/data/coco
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-object-detection-spr-maskrcnn-training
  cmd: quickstart/training.sh bf16
  env:
    PRECISION: bf16
    BATCH_SIZE: '56'
    OUTPUT_DIR: /tmp
    DATASET_DIR: /localdisk/sharvils/data/coco
  volumes:
    - src: /localdisk/sharvils/data/coco
      dst: /localdisk/sharvils/data/coco
