fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: bash run_model.sh
  env:
    PRECISION: fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
    TEST_MODE: REALTIME
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
    - src: /tmp
      dst: /tmp
