{% set name = "cloud-data-connector" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloud_data_connector-{{ version }}.tar.gz
  sha256: c0e23333b9d3b021a94516dc4a67b47abbdd18c5f011ceec834acd2b673988a5

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python>=3.8,<3.11
    - setuptools>=61.0
    - setuptools-scm
    - pip
  run:
    - python>=3.8,<3.11
    # - azureml>=0.2.7 # not available in conda
    - azure-ai-ml>=2023.06.01 # microsoft only
    - azure-core>=2023.06.01
    - azure-identity>=2023.06.01
    - azure-storage-blob>=1.4.1
    # - azureml-core>=1.49.0 # not available in conda
    - boto3>=1.26.154
    - google-api-core>=2.0.0
    - google-auth>=1.33.0
    - google-auth-oauthlib>=0.4.1
    - google-cloud-bigquery>=2.1.0
    - google-cloud-storage>=2.1.0
    - packaging>=21.3
    - python-dotenv>=1.0.0

test:
  imports:
    - data_connector

about:
  summary: 'Data connector is a tool to connect to AzureML, Azure blob, GCP storage, GCP Big Query and AWS storage S3. The goal is provide all cloud managers in one place and provide documentation for an easy integration.'
  license: 'Apache License, Version 2.0'
  about_license_url: https://www.apache.org/licenses/LICENSE-2.0.html

extra:
  recipe-maintainers:
    - Jose de Jesus Herrera Ledon <jesus.herrera.ledon@intel.com>
    - Alberto Gallegos Muro <alberto.gallegos.muro@intel.com>
    - Felipe Leza Alvarez <felipe.leza.alvarez@intel.com>
    - Miguel Pineda Juarez <miguel.pineda.juarez@intel.com>
    - Gerardo Dominguez Aldama <gerardo.dominguez.aldama@intel.com>
