fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-training
  cmd: quickstart/training.sh fp32
  shm-size: 8G
  env: 
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-training
  cmd: quickstart/training.sh bf16
  shm-size: 8G
  env: 
    PRECISION: bf16
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
