fp32-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-inference
  cmd: quickstart/accuracy.sh fp32
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
  volumes:
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
fp16-accuracy:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-inference
  cmd: quickstart/accuracy.sh fp16
  shm-size: 8G
  env:
    PRECISION: fp16
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
  volumes:
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
fp32-realtime:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-inference
  cmd: quickstart/accuracy.sh fp32
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
  volumes:
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
fp16-realtime:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-inference
  cmd: quickstart/inference_realtime.sh fp16
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
  volumes:
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
fp32-throughput:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-inference
  cmd: quickstart/inference_throughput.sh fp32
  shm-size: 8G
  env:
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
  volumes:
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
fp16-throughput:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-language-modeling-rnnt-inference
  cmd: quickstart/inference_throughput.sh fp16
  shm-size: 8G
  env:
    PRECISION: fp16
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/rnnt_dataset
  volumes:
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
    - src: /pytorch/rnnt_dataset
      dst: /pytorch/rnnt_dataset
