fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-training
  cmd: quickstart/training.sh fp32
  ipc: host
  env: 
    PRECISION: fp32
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    RESULT_DIR: /tmp
    NUM_STEPS: '100'
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-training
  cmd: quickstart/training.sh bf16
  ipc: host
  env: 
    PRECISION: bf16
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    RESULT_DIR: /tmp
    NUM_STEPS: '100'
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
bf32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-rnnt-training
  cmd: quickstart/training.sh bf32
  ipc: host
  env: 
    PRECISION: bf32
    CHECKPOINT_DIR: /pytorch/rnnt_model
    OUTPUT_DIR: /tmp
    RESULT_DIR: /tmp
    NUM_STEPS: '100'
    DATASET_DIR: /pytorch/rnnt_dataset_training
  volumes:
    - src: /pytorch/rnnt_dataset_training
      dst: /pytorch/rnnt_dataset_training
    - src: /pytorch/rnnt_model
      dst: /pytorch/rnnt_model
