---
tf-flex-gpu-stable-diffusion-inference:
  image_name: intel/generative-ai:tf-flex-gpu-stable-diffusion-inference
  tests:
  - test_name: stable-diffusion FP32 inference
    env_vars:
      SCRIPT: quickstart/online_inference.sh
      BATCH_SIZE: 1
      PRECISION: fp32
      OUTPUT_DIR: /output/tf-flex-gpu-stable-diffusion-inference
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      OUTPUT_DIR: /output/tf-flex-gpu-stable-diffusion-inference
  - test_name: stable-diffusion FP16 inference
    env_vars:
      SCRIPT: quickstart/online_inference.sh
      BATCH_SIZE: 1
      PRECISION: fp16
      OUTPUT_DIR: /output/tf-flex-gpu-stable-diffusion-inference
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      OUTPUT_DIR: /output/tf-flex-gpu-stable-diffusion-inference
  - test_name: stable-diffusion FP16 Accuracy
    env_vars:
      SCRIPT: quickstart/accuracy.sh
      BATCH_SIZE: 1
      PRECISION: fp16
      REFERENCE_RESULT_FILE: /tf_dataset/nv_results/img_arrays_for_acc.txt
      OUTPUT_DIR: /output/tf-flex-gpu-stable-diffusion-inference
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      OUTPUT_DIR: /output/tf-flex-gpu-stable-diffusion-inference
      REFERENCE_RESULT_FILE: /tf_dataset/nv_results/img_arrays_for_acc.txt
