releases:
  versioned:
    tag_specs:
    - '{spr-mobilenet-v1-inference}'
slice_sets:
  spr-mobilenet-v1-inference:
    - add_to_name: tf-spr-mobilenet-v1-inference
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-mobilenet-v1-inference
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
      partials:
        - tensorflow/tensorflow-base
        - model_package
        - numactl
        - entrypoint
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/image_recognition/__init__.py
          source: benchmarks/image_recognition/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/__init__.py
          source: benchmarks/image_recognition/tensorflow/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/mobilenet_v1/__init__.py
          source: benchmarks/image_recognition/tensorflow/mobilenet_v1/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference/__init__.py
          source: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference/__init__.py
        - destination: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference
          source: benchmarks/image_recognition/tensorflow/mobilenet_v1/inference
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - source: quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/inference_realtime_multi_instance.sh
          destination: quickstart/inference_realtime.sh
        - source: quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/inference_throughput_multi_instance.sh
          destination: quickstart/inference_throughput.sh
        - source: quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/accuracy.sh
          destination: quickstart/accuracy.sh
        - destination: models/common
          source: models/common
        - destination: models/image_recognition/tensorflow/mobilenet_v1
          source: models/image_recognition/tensorflow/mobilenet_v1
        - destination: quickstart/common
          source: quickstart/common
      downloads:
      - source: https://ubit-artifactory-or.intel.com/artifactory/cicd-or-local/model-zoo/spr/2022/tensorflow/ww18/tf_dataset/pre-trained-models/mobilenet_v1/int8/mobilenetv1_int8_pretrained_model_new.pb
        destination: pretrained_model/mobilenet_v1_int8_pretrained_model.pb
      - source: https://ubit-artifactory-or.intel.com/artifactory/cicd-or-local/model-zoo/spr/2022/tensorflow/ww18/tf_dataset/pre-trained-models/mobilenet_v1/fp32/mobilenetv1_fp32_pretrained_model_new.pb
        destination: pretrained_model/mobilenet_v1_bfloat16_pretrained_model.pb
      - source: https://ubit-artifactory-or.intel.com/artifactory/cicd-or-local/model-zoo/spr/2022/tensorflow/ww18/tf_dataset/pre-trained-models/mobilenet_v1/fp32/mobilenetv1_fp32_pretrained_model_new.pb
        destination: pretrained_model/mobilenet_v1_fp32_pretrained_model.pb
      wrapper_package_files:
        - source: output/tf-spr-mobilenet-v1-inference.tar.gz
          destination: model_packages/tf-spr-mobilenet-v1-inference.tar.gz
        - source: quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/build.sh
          destination: build.sh
        - source: quickstart/image_recognition/tensorflow/mobilenet_v1/inference/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-mobilenet-v1-inference.Dockerfile
          destination: tf-spr-mobilenet-v1-inference.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
