releases:
  versioned:
    tag_specs:
    - '{spr-dien-training}'
slice_sets:
  tf-spr-dien-training:
  - add_to_name:  tf-spr-dien-training
    args:
    - PACKAGE_NAME= tf-spr-dien-training
    dockerfile_subdirectory: tensorflow-spr
    documentation:
      - docs:
        - name: Title
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/title.md
        - name: Description
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/description.md
        - name: Datasets
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/datasets.md
        - name: Quick Start Scripts
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/quickstart.md
        - name: Docker
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/docker_spr.md
        - name: License
          uri: models/quickstart/recommendation/tensorflow/dien/training/cpu/.docs/license.md
        name: README_SPR_container.md
        text_replace:
         <docker image>: model-zoo:tf-spr-dien-training
          <mode>: training
          <model name>: DIEN
          <use case>: recommendation
        uri: models/quickstart/recommendation/tensorflow/dien/training/cpu
    wrapper_package_files:
        - source: output/tf-spr-dien-training.tar.gz
          destination: model_packages/tf-spr-dien-training.tar.gz
        - source: quickstart/recommendation/tensorflow/dien/training/cpu/build.sh
          destination: build.sh
        - source: quickstart/recommendation/tensorflow/dien/training/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-dien-training.Dockerfile
          destination: tf-spr-dien-training.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/recommendation/tensorflow/dien/training/cpu/README_SPR_container.md
          destination: README.md
    files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/recommendation/__init__.py
          source: benchmarks/recommendation/__init__.py
        - destination: benchmarks/recommendation/tensorflow/__init__.py
          source: benchmarks/recommendation/tensorflow/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/__init__.py
          source: benchmarks/recommendation/tensorflow/dien/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/training/__init__.py
          source: benchmarks/recommendation/tensorflow/dien/training/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/training
          source: benchmarks/recommendation/tensorflow/dien/training
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - destination: models/common
          source: models/common
        - destination: models/recommendation/tensorflow/dien/training
          source: models/recommendation/tensorflow/dien/training
        - destination: quickstart/common
          source: quickstart/common
        - destination: quickstart/training.sh
          source: quickstart/recommendation/tensorflow/dien/training/cpu/training.sh
