releases:
  versioned:
    tag_specs:
    - '{spr-dien-inference}'
slice_sets:
  spr-dien-inference:
    - add_to_name: tf-spr-dien-inference
      dockerfile_subdirectory: tensorflow-spr
      args:
        - PACKAGE_NAME=tf-spr-dien-inference
        - TENSORFLOW_IMAGE=model-zoo
        - TENSORFLOW_TAG=tensorflow-spr
      partials:
        - tensorflow/tensorflow-base
        - model_package
        - numactl
        - entrypoint
      files:
        - destination: benchmarks/common
          source: benchmarks/common
        - destination: benchmarks/recommendation/__init__.py
          source: benchmarks/recommendation/__init__.py
        - destination: benchmarks/recommendation/tensorflow/__init__.py
          source: benchmarks/recommendation/tensorflow/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/inference/README.md
          source: benchmarks/recommendation/tensorflow/dien/inference/README.md
        - destination: benchmarks/recommendation/tensorflow/dien/__init__.py
          source: benchmarks/recommendation/tensorflow/dien/__init__.py
        - destination: benchmarks/recommendation/tensorflow/dien/inference
          source: benchmarks/recommendation/tensorflow/dien/inference
        - destination: benchmarks/launch_benchmark.py
          source: benchmarks/launch_benchmark.py
        - source: quickstart/recommendation/tensorflow/dien/inference/cpu/inference_realtime_multi_instance.sh
          destination: quickstart/inference_realtime.sh
        - source: quickstart/recommendation/tensorflow/dien/inference/cpu/inference_throughput_multi_instance.sh
          destination: quickstart/inference_throughput.sh
        - source: quickstart/recommendation/tensorflow/dien/inference/cpu/accuracy.sh
          destination: quickstart/accuracy.sh
        - destination: models/common
          source: models/common
        - destination: models/recommendation/tensorflow/dien/inference
          source: models/recommendation/tensorflow/dien/inference
        - destination: quickstart/common
          source: quickstart/common
      downloads:
      - source: https://ubit-artifactory-or.intel.com/artifactory/cicd-or-local/model-zoo/spr/2022/tensorflow/ww18/tf_dataset/pre-trained-models/dien/fp32/dien_fp32_static_rnn_graph.pb
        destination: pretrained_model/dien_fp32_static_rnn_graph.pb
      wrapper_package_files:
        - source: output/tf-spr-dien-inference.tar.gz
          destination: model_packages/tf-spr-dien-inference.tar.gz
        - source: quickstart/recommendation/tensorflow/dien/inference/cpu/build.sh
          destination: build.sh
        - source: quickstart/recommendation/tensorflow/dien/inference/cpu/run.sh
          destination: run.sh
        - source: dockerfiles/tensorflow-spr/tf-spr-dien-inference.Dockerfile
          destination: tf-spr-dien-inference.Dockerfile
        - source: LICENSE
          destination: licenses/LICENSE
        - source: third_party
          destination: licenses/third_party
        - source: quickstart/recommendation/tensorflow/dien/inference/cpu/README_SPR_container.md
          destination: README.md
      documentation:
        - docs:
          - name: Title
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/title.md
          - name: Description
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/description.md
          - name: Model Package
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/wrapper_package.md
          - name: Quickstart
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/quickstart_spr.md
          - name: Datasets
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/datasets.md
          - name: Container build
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/container_build.md
          - name: Docker
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/docker_spr.md
          - name: License
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/license.md
          name: README_SPR_container.md
          text_replace:
            <model name>: DIEN
            <mode>: inference
            <package name>: tf-spr-dien-inference.tar.gz
            <package dir>: tf-spr-dien-inference
            <docker image>: model-zoo:tf-spr-dien-inference
          uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu
        - docs:
          - name: Title
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/title.md
          - name: Description
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/description.md
          - name: Baremetal setup SPR
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/baremetal_setup_spr.md
          - name: Quickstart
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/quickstart_spr.md
          - name: Datasets
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/datasets.md
          - name: Baremetal SPR
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/baremetal_spr.md
          - name: License
            uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu/.docs/license.md
          name: README_SPR_baremetal.md
          text_replace:
            <model name>: DIEN
            <mode>: inference
          uri: models/quickstart/recommendation/tensorflow/dien/inference/cpu
