fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_realtime.sh fp32 jit
  env:
    PRECISION: fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_throughput.sh fp32 jit
  env:
    PRECISION: fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/accuracy.sh fp32 jit
  env:
    PRECISION: fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
avx-fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_realtime.sh avx-fp32 jit
  env:
    PRECISION: avx-fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
avx-fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_throughput.sh avx-fp32 jit
  env:
    PRECISION: avx-fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
avx-fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/accuracy.sh avx-fp32 jit
  env:
    PRECISION: avx-fp32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_realtime.sh bf16 jit
  env:
    PRECISION: bf16
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_throughput.sh bf16 jit
  env:
    PRECISION: bf16
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/accuracy.sh bf16 jit
  env:
    PRECISION: bf16
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_realtime.sh bf32 jit
  env:
    PRECISION: bf16
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/inference_throughput.sh bf32 jit
  env:
    PRECISION: bf32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
bf32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-object-detection-maskrcnn-inference
  cmd: quickstart/accuracy.sh bf32 jit
  env:
    PRECISION: bf32
    MODE: jit
    CHECKPOINT_DIR: /pytorch/pretrained_models/maskrcnn
    OUTPUT_DIR: /tmp
    DATASET_DIR: /pytorch/coco
  volumes:
    - src: /pytorch/coco
      dst: /pytorch/coco
    - src: /pytorch/pretrained_models/maskrcnn
      dst: /pytorch/pretrained_models/maskrcnn
