---
tf-flex-gpu-maskrcnn-inference:
  image_name: intel/image-segmentation:tf-flex-gpu-maskrcnn-inference
  tests:
  - test_name: maskrcnn FP16 Online inference
    env_vars:
      SCRIPT: quickstart/inference.sh
      BATCH_SIZE: 1
      PRECISION: fp16
      DATASET_DIR: /tf_dataset/dataset/coco_dataset/COCO2017_training_data
      OUTPUT_DIR: /output/tf-flex-gpu-maskrcnn-inference
      PRETRAINED_DIR: /workspace/tf-flex-series-maskrcnn-inference/pretrained_weights
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      DATASET_DIR: /tf_dataset/dataset/coco_dataset/COCO2017_training_data
      OUTPUT_DIR: /output/tf-flex-gpu-maskrcnn-inference
  - test_name: maskrcnn FP16 Batch inference
    env_vars:
      SCRIPT: quickstart/inference.sh
      BATCH_SIZE: 16
      PRECISION: fp16
      DATASET_DIR: /tf_dataset/dataset/coco_dataset/COCO2017_training_data
      OUTPUT_DIR: /output/tf-flex-gpu-maskrcnn-inference
      PRETRAINED_DIR: /workspace/tf-flex-series-maskrcnn-inference/pretrained_weights
      DOCKER_ARGS: --ipc=host --privileged --device=/dev/dri
    volumes:
      DATASET_DIR: /tf_dataset/dataset/coco_dataset/COCO2017_training_data
      OUTPUT_DIR: /output/tf-flex-gpu-maskrcnn-inference
