fp32-realtime:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-language-modeling-distilbert-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    TEST_MODE: REALTIME
    SEQUENCE_LENGTH: '128'
    CORE_PER_INSTANCE: '4'
    HF_DATASETS_OFFLINE: '0'
    OUTPUT_DIR: /tmp
    FINETUNED_MODEL: /pytorch/pretrained_models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/
    DATASET_DIR: /pytorch/distilbert_dataset/SST-2/
  volumes:
    - src: /pytorch/distilbert_dataset/SST-2/
      dst: /pytorch/distilbert_dataset/SST-2/
    - src: /pytorch/pretrained_models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/
      dst: /pytorch/pretrained_models/distilbert/distilbert-base-uncased-finetuned-sst-2-english/
    - src: /tmp
      dst: /tmp
